# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/replication.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc/replication.proto\x12\x0breplication\":\n\x1aRegisterCoordinatorRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"\x1d\n\x1bRegisterCoordinatorResponse\")\n\x15GetCoordinatorRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\"$\n\x16GetCoordinatorResponse\x12\n\n\x02ip\x18\x01 \x01(\t\"<\n\x1cUnregisterCoordinatorRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"\x1f\n\x1dUnregisterCoordinatorResponse\"H\n\x19SetReplicationPeerRequest\x12\x18\n\x10local_mountpoint\x18\x01 \x01(\t\x12\x11\n\ttarget_ip\x18\x02 \x01(\t\"\x1c\n\x1aSetReplicationPeerResponse\"1\n\x15MountGCSBucketRequest\x12\x18\n\x10local_mountpoint\x18\x01 \x01(\t\"\x18\n\x16MountGCSBucketResponse\".\n\x12UnmountPeerRequest\x12\x18\n\x10local_mountpoint\x18\x01 \x01(\t\"\x15\n\x13UnmountPeerResponse\"\x18\n\x16UnmountAllPeersRequest\"\x19\n\x17UnmountAllPeersResponse2\xc9\x05\n\x12ReplicationService\x12j\n\x13RegisterCoordinator\x12\'.replication.RegisterCoordinatorRequest\x1a(.replication.RegisterCoordinatorResponse\"\x00\x12[\n\x0eGetCoordinator\x12\".replication.GetCoordinatorRequest\x1a#.replication.GetCoordinatorResponse\"\x00\x12p\n\x15UnregisterCoordinator\x12).replication.UnregisterCoordinatorRequest\x1a*.replication.UnregisterCoordinatorResponse\"\x00\x12g\n\x12SetReplicationPeer\x12&.replication.SetReplicationPeerRequest\x1a\'.replication.SetReplicationPeerResponse\"\x00\x12[\n\x0eMountGCSBucket\x12\".replication.MountGCSBucketRequest\x1a#.replication.MountGCSBucketResponse\"\x00\x12R\n\x0bUnmountPeer\x12\x1f.replication.UnmountPeerRequest\x1a .replication.UnmountPeerResponse\"\x00\x12^\n\x0fUnmountAllPeers\x12#.replication.UnmountAllPeersRequest\x1a$.replication.UnmountAllPeersResponse\"\x00\x42TZRgke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/replicationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/replication'
  _globals['_REGISTERCOORDINATORREQUEST']._serialized_start=38
  _globals['_REGISTERCOORDINATORREQUEST']._serialized_end=96
  _globals['_REGISTERCOORDINATORRESPONSE']._serialized_start=98
  _globals['_REGISTERCOORDINATORRESPONSE']._serialized_end=127
  _globals['_GETCOORDINATORREQUEST']._serialized_start=129
  _globals['_GETCOORDINATORREQUEST']._serialized_end=170
  _globals['_GETCOORDINATORRESPONSE']._serialized_start=172
  _globals['_GETCOORDINATORRESPONSE']._serialized_end=208
  _globals['_UNREGISTERCOORDINATORREQUEST']._serialized_start=210
  _globals['_UNREGISTERCOORDINATORREQUEST']._serialized_end=270
  _globals['_UNREGISTERCOORDINATORRESPONSE']._serialized_start=272
  _globals['_UNREGISTERCOORDINATORRESPONSE']._serialized_end=303
  _globals['_SETREPLICATIONPEERREQUEST']._serialized_start=305
  _globals['_SETREPLICATIONPEERREQUEST']._serialized_end=377
  _globals['_SETREPLICATIONPEERRESPONSE']._serialized_start=379
  _globals['_SETREPLICATIONPEERRESPONSE']._serialized_end=407
  _globals['_MOUNTGCSBUCKETREQUEST']._serialized_start=409
  _globals['_MOUNTGCSBUCKETREQUEST']._serialized_end=458
  _globals['_MOUNTGCSBUCKETRESPONSE']._serialized_start=460
  _globals['_MOUNTGCSBUCKETRESPONSE']._serialized_end=484
  _globals['_UNMOUNTPEERREQUEST']._serialized_start=486
  _globals['_UNMOUNTPEERREQUEST']._serialized_end=532
  _globals['_UNMOUNTPEERRESPONSE']._serialized_start=534
  _globals['_UNMOUNTPEERRESPONSE']._serialized_end=555
  _globals['_UNMOUNTALLPEERSREQUEST']._serialized_start=557
  _globals['_UNMOUNTALLPEERSREQUEST']._serialized_end=581
  _globals['_UNMOUNTALLPEERSRESPONSE']._serialized_start=583
  _globals['_UNMOUNTALLPEERSRESPONSE']._serialized_end=608
  _globals['_REPLICATIONSERVICE']._serialized_start=611
  _globals['_REPLICATIONSERVICE']._serialized_end=1324
# @@protoc_insertion_point(module_scope)
