# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc import replication_pb2 as rpc_dot_replication__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rpc/replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ReplicationServiceStub(object):
    """The gRPC service for replication worker operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCoordinator = channel.unary_unary(
                '/replication.ReplicationService/RegisterCoordinator',
                request_serializer=rpc_dot_replication__pb2.RegisterCoordinatorRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.RegisterCoordinatorResponse.FromString,
                _registered_method=True)
        self.GetCoordinator = channel.unary_unary(
                '/replication.ReplicationService/GetCoordinator',
                request_serializer=rpc_dot_replication__pb2.GetCoordinatorRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.GetCoordinatorResponse.FromString,
                _registered_method=True)
        self.UnregisterCoordinator = channel.unary_unary(
                '/replication.ReplicationService/UnregisterCoordinator',
                request_serializer=rpc_dot_replication__pb2.UnregisterCoordinatorRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.UnregisterCoordinatorResponse.FromString,
                _registered_method=True)
        self.SetReplicationPeer = channel.unary_unary(
                '/replication.ReplicationService/SetReplicationPeer',
                request_serializer=rpc_dot_replication__pb2.SetReplicationPeerRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.SetReplicationPeerResponse.FromString,
                _registered_method=True)
        self.MountGCSBucket = channel.unary_unary(
                '/replication.ReplicationService/MountGCSBucket',
                request_serializer=rpc_dot_replication__pb2.MountGCSBucketRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.MountGCSBucketResponse.FromString,
                _registered_method=True)
        self.UnmountPeer = channel.unary_unary(
                '/replication.ReplicationService/UnmountPeer',
                request_serializer=rpc_dot_replication__pb2.UnmountPeerRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.UnmountPeerResponse.FromString,
                _registered_method=True)
        self.UnmountAllPeers = channel.unary_unary(
                '/replication.ReplicationService/UnmountAllPeers',
                request_serializer=rpc_dot_replication__pb2.UnmountAllPeersRequest.SerializeToString,
                response_deserializer=rpc_dot_replication__pb2.UnmountAllPeersResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """The gRPC service for replication worker operations
    """

    def RegisterCoordinator(self, request, context):
        """Discovery methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReplicationPeer(self, request, context):
        """Replication methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MountGCSBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnmountPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnmountAllPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCoordinator,
                    request_deserializer=rpc_dot_replication__pb2.RegisterCoordinatorRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.RegisterCoordinatorResponse.SerializeToString,
            ),
            'GetCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoordinator,
                    request_deserializer=rpc_dot_replication__pb2.GetCoordinatorRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.GetCoordinatorResponse.SerializeToString,
            ),
            'UnregisterCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterCoordinator,
                    request_deserializer=rpc_dot_replication__pb2.UnregisterCoordinatorRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.UnregisterCoordinatorResponse.SerializeToString,
            ),
            'SetReplicationPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReplicationPeer,
                    request_deserializer=rpc_dot_replication__pb2.SetReplicationPeerRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.SetReplicationPeerResponse.SerializeToString,
            ),
            'MountGCSBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.MountGCSBucket,
                    request_deserializer=rpc_dot_replication__pb2.MountGCSBucketRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.MountGCSBucketResponse.SerializeToString,
            ),
            'UnmountPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.UnmountPeer,
                    request_deserializer=rpc_dot_replication__pb2.UnmountPeerRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.UnmountPeerResponse.SerializeToString,
            ),
            'UnmountAllPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.UnmountAllPeers,
                    request_deserializer=rpc_dot_replication__pb2.UnmountAllPeersRequest.FromString,
                    response_serializer=rpc_dot_replication__pb2.UnmountAllPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """The gRPC service for replication worker operations
    """

    @staticmethod
    def RegisterCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/RegisterCoordinator',
            rpc_dot_replication__pb2.RegisterCoordinatorRequest.SerializeToString,
            rpc_dot_replication__pb2.RegisterCoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/GetCoordinator',
            rpc_dot_replication__pb2.GetCoordinatorRequest.SerializeToString,
            rpc_dot_replication__pb2.GetCoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/UnregisterCoordinator',
            rpc_dot_replication__pb2.UnregisterCoordinatorRequest.SerializeToString,
            rpc_dot_replication__pb2.UnregisterCoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReplicationPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/SetReplicationPeer',
            rpc_dot_replication__pb2.SetReplicationPeerRequest.SerializeToString,
            rpc_dot_replication__pb2.SetReplicationPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MountGCSBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/MountGCSBucket',
            rpc_dot_replication__pb2.MountGCSBucketRequest.SerializeToString,
            rpc_dot_replication__pb2.MountGCSBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnmountPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/UnmountPeer',
            rpc_dot_replication__pb2.UnmountPeerRequest.SerializeToString,
            rpc_dot_replication__pb2.UnmountPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnmountAllPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/UnmountAllPeers',
            rpc_dot_replication__pb2.UnmountAllPeersRequest.SerializeToString,
            rpc_dot_replication__pb2.UnmountAllPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
